### ISSUE TITLE
Package installation fails with npm<3.0.0

### ISSUE THREAD

**Issue by AndreyBelym** [inikulin/publish-please#35]
`npm` at versions lower than 3.0.0 can execute `postinstall` scripts before package dependencies was installed: https://github.com/npm/npm/issues/6926. Due to `babel`ified `lib/init.js`, that requires `babel-runtime` and `core-js`, it sometimes causes the following error:
```
> publish-please@2.1.3 postinstall /home/travis/build/testcafe-build-bot/testcafe/node_modules/publish-please
> node lib/init.js
module.js:340
    throw err;
          ^
Error: Cannot find module '../../modules/_core'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/travis/build/testcafe-build-bot/testcafe/node_modules/babel-runtime/node_modules/core-js/library/fn/json/stringify.js:1:75)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by inikulin** [comment]
Published as `v2.1.4`
